# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

shared:
  image: quay.io/centos/centos:stream8
  environment:
    PYVESPA_VERSION: 0.7
  annotations:
    screwdriver.cd/timeout: 30
    screwdriver.cd/cpu: HIGH
    screwdriver.cd/ram: HIGH
    screwdriver.cd/dockerEnabled: true
    screwdriver.cd/dockerCpu: HIGH
    screwdriver.cd/dockerRam: HIGH
    screwdriver.cd/buildPeriodically: H 11 * * *

jobs:
  tests:
    requires: [~commit,~pr]
    steps:
      - setup: |
          export WORK_DIR=$SD_DIND_SHARE_PATH
          export RESOURCES_DIR=$(pwd)/resources
      - install-docker: |
          dnf install -y dnf-plugins-core
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli
          docker system info
          ls -la $SD_DIND_SHARE_PATH
      - install-python: |
          dnf install -y python39-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          python3 -m pip install -e .[full]
      - run-tests: |
          pytest learntorank/test_*.py -s -v
